feat!: create a server version of peacock
spring-financial-group/peacock pull request #45
Opened 2023-01-06 12:36 UTC by Skisocks

2023-01-06 14:23 UTC, Skisocks commented
/test pr

2023-01-06 14:28 UTC, Skisocks commented
/test pr

2023-01-09 22:01 UTC, Skisocks commented
/test pr

2023-01-11 10:43 UTC, Skisocks commented
/test pr

2023-01-17 15:02 UTC, Skisocks commented
/peacock-verify

2023-01-17 15:02 UTC, Skisocks commented
/test peacock-verify

2023-01-17 17:26 UTC, Skisocks commented
/retest

2023-01-17 21:47 UTC, Skisocks commented
/test peacock-verify

2023-01-17 21:49 UTC, Skisocks commented
/test peacock-release

2023-01-17 21:50 UTC, Skisocks commented
/test peacock-release-test

2023-01-18 15:22 UTC, tomhobson requested changes

2023-01-18 15:22 UTC, tomhobson commented on .lighthouse/jenkins-x/peacock/verify.yaml
> +
whitespace

2023-01-18 15:23 UTC, tomhobson requested changes

2023-01-18 15:23 UTC, tomhobson commented on .lighthouse/jenkins-x/peacock/release.yaml
> +
Whitespace

2023-01-18 15:59 UTC, tomhobson requested changes

2023-01-18 15:59 UTC, tomhobson commented on charts/peacock/Chart.yaml
> +version: 0.1.0-SNAPSHOT
Should we get the image rocking and rolling?

2023-01-18 15:59 UTC, tomhobson commented on charts/peacock/values.yaml
> +      secretName: ""
does this make it jx native?

2023-01-18 15:59 UTC, tomhobson commented on pkg/cmd/run/run.go
> +	MSGHandler      domain.MessageHandler
MessageHandler?

2023-01-18 15:59 UTC, tomhobson commented on pkg/git/github/client.go
> +	// If there is only one PR then that must be is
`Then that must be is`

2023-01-18 15:59 UTC, tomhobson commented on pkg/health/health.go
> +	// Todo: Add health checks for other dependencies
:) Fine because this a POC, but we should maybe add some health stuff

2023-01-18 15:59 UTC, tomhobson commented on pkg/message/message.go
> +
Feel like this should be in a config or a constant at least

2023-01-18 15:59 UTC, tomhobson commented on pkg/msgclient/handler.go
> +		clients[models.Webhook] = webhook.NewClient(cfg.Webhook.URL, cfg.Webhook.Token, cfg.Webhook.Secret)
What happens if they are empty?

2023-01-18 15:59 UTC, tomhobson commented on pkg/server/data.go
> +}
Is this just a proxy method? I'm not really sure what this is doing?

2023-01-18 21:11 UTC, tomhobson approved these changes

2023-01-18 21:21 UTC, Skisocks commented
wut
/test peacock-verify

2023-01-18 21:22 UTC, Skisocks commented
Did I push the git token?

2023-01-18 21:22 UTC, Skisocks commented
/test pr

2023-01-18 21:25 UTC, Skisocks commented
Secrets must have been having a nap

2023-01-18 21:26 UTC, merged